language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
script:
- python setup.py test
- sed -i "s/MEDIA_PLATFORM_SDK_VERSION/$(git describe --abbrev=0 --tags)/g" setup.py
deploy:
  provider: pypi
  user: wixmcloud
  skip_existing: true
  password:
    secure: WWdcVNpUn7KzLRVzc1r4Nxqt4CtdQ0h35ewAwalP0FK3JUnXHV2L9SpjvynOKs2k3oiV9HjIYSteV0Vux9E3kCyY8wzLk7RvPmHd1GUwgB1CRf7m0UB5Vygg1yFr4nYMLDXrrTvbHcoP6mq03hHzXwL9Zfv1TNTPMKsLxvtN8l+ZDOIu8PepAZfexKVbcw0nyk69THborDnFUQ8JYyMTYYR5p/j6FQP6DsU78mwyqHcP4uzI85JQOWGwxBTkX94IftUmqF20ZfIR/6pFYogdPhhnwa37q823uNS8a8n1TgWQ8+7WUcjh/PNe1h+0B64ERcRreecAzUldLw809fzCvj6allUccdJZM11VC1WYDJJGXwgUT7CbSm5kweD1kZ4k7cMxhynOq4anuaSj1VTrY45ZeDeFtpeUsle/M5x52SuMLLJOemVOK2OC7VZ96WFB6uhMlxCOVGZqD5c6oqSbcJQPiqOVlWPFe0bD9Qfl6/YA5tOIkgP1Rn94SpcfZQSOdOJDDJGG8VYhY5AS4+hXjahPkVcgCmDcIFqqOfYjN7ITr7uOIXecQgmUAViMt1SC69tXxiT7FFDMUyv9QwwHZf86dQ6xnhclXENVK/YYWshadI6PTkIj4ZjPH5qv7fWvBqxp+//ku2qIest15jj8bF7kgT8IC8KvKJwnUr1FFSM=
#  on:
#    tags: true
#    condition: tag =~ /^release-/
on:
  all_branches: true
  condition: $TRAVIS_TAG =~ ^release-
